version: "3"
services:
  db:
    image: postgres
    volumes:
      - starlette-postgresql-data:/var/lib/postgresql
    container_name: starlette-postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB

volumes:
  starlette-postgresql-data:
